### ISSUE TITLE
Unknown timezone when using eva console

### ISSUE THREAD

**Issue by AlexMKX** [eva-ics/eva4#14]
Steps to reproduce:

``` shell
(venv) root@local-eva-ics:/# export TZ=Asia/Riyadh && eva
Traceback (most recent call last):
  File "/opt/eva4/venv/bin/eva", line 3, in <module>
    import eva4_shell.shell as shell
  File "/opt/eva4/venv/lib/python3.8/site-packages/eva4_shell/shell.py", line 5, in <module>
    from .sharedobj import common, current_command
  File "/opt/eva4/venv/lib/python3.8/site-packages/eva4_shell/sharedobj.py", line 14, in <module>
    TZ=pytz.timezone(time.tzname[0]))
  File "/opt/eva4/venv/lib/python3.8/site-packages/pytz/__init__.py", line 188, in timezone
    raise UnknownTimeZoneError(zone)
pytz.exceptions.UnknownTimeZoneError: '+03'

```
Expected result: console working properly.

**Comment by divi255** [comment]
Fixed in eva-shell 0.2.15 and will be included into the next v4 stable.

For the moment is a solution to update eva-shell only:

```shell
/opt/eva4/sbin/venvmgr update eva-shell
```
