### ISSUE TITLE
eva4-svc-controller-py do not honor absolute path

### ISSUE THREAD

**Issue by AlexMKX** [eva-ics/eva4#15]
Service config:
```  svcs: 
  - id: eva.controller.py
    params:
      command: venv/bin/eva4-svc-controller-py
      bus:
        path: var/bus.ipc
      config:
        macro_dir: /homeassistant/addons/eva_ics
      user: nobody
```
Expected result: 
controller looks for macros using absolute paths.

Result:
controller appends path to the default one:

``` 2024-02-19T06:02:17+01:00 local-eva-ics  ERROR eva::svc eva.controller.py mod:__init__ fn:safe_run_macro th:ThreadPoolExecutor-0_0 :: Traceback (most recent call last):
  File "/opt/eva4/venv/lib/python3.8/site-packages/eva4_controller_py/__init__.py", line 113, in safe_run_macro
    run_macro(i, args, kwargs, timeout, env)
  File "/opt/eva4/venv/lib/python3.8/site-packages/eva4_controller_py/__init__.py", line 86, in run_macro
    code = compiler.compile(fname)
  File "/opt/eva4/venv/lib/python3.8/site-packages/eva4_controller_py/__init__.py", line 43, in compile
    mtime = os.path.getmtime(fname)
  File "/usr/lib/python3.8/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/opt/eva4/runtime//homeassistant/addons/eva_ics/room1.fan_control.py'

```

**Comment by divi255** [comment]
Added in eva4-controller-py 0.1.3, for existing systems please update the module:

/opt/eva4/sbin/venvmgr update eva4-controller-py
